twitter:
    name: 'callieburke'
    consumer_key: 'ZVIgrKzFHV0s7MkUPsUaRxSB0'
    consumer_secret: '8ZvyhbwenIBiiDZX2V5jbfCyClvliVX08nBmKCJWs8JthZDapL'
    oauth_token: '30171655-TFN84aT0l0qqI5BgxCCko9Ueg2iHNCOlFPQhmBiw2'
    oauth_token_secret:'nGsiCp8tgYZ90CbDSfDjgB4ytCnF9GqXbb40XLetkGPpi'